eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-srsj-console
#logbackConfigLocation: classpath:logback.xml
logging.config: classpath:logback.xml
