server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: service-srsj-console

#eureka:
#  instance:
#    hostname: ${HOST_LOCAL:localhost}
  #    prefer-ip-address: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://${HOST_NAME:ubuntu1}:${server.port}/eureka/

#logbackConfigLocation: classpath:logback.xml
logging.config: classpath:logback.xml

rtmp.port: ${RTMP_PORT:1935}
http.port: ${HTTP_PORT:8762}

